import random

VERBS = [
    "Loading",
    "Crunching",
    "Whirring",
    "Fetching",
    "Percolating",
    "Assembling",
    "Compiling",
    "Scanning",
    "Indexing",
    "Syncing",
    "Warming",
    "Tuning",
    "Polishing",
    "Flushing",
    "Stitching",
    "Analyzing",
    "Rendering",
    "Merging",
    "Filtering",
    "Booting",
    "Wiring",
    "Balancing",
    "Purring",
    "Motoring",
    "Shuffling",
    "Sifting",
    "Preparing",
    "Rehydrating",
    "Threading",
    "Bubbling",
    "Steaming",
    "Cycling",
    "Calibrating",
    "Popping",
    "Glowing",
    "Humming",
    "Sparking",
    "Resizing",
    "Orbiting",
    "Docking",
    "Weaving",
    "Building",
    "Sculpting",
    "Tracing",
    "Pruning",
    "Lining",
    "Packing",
    "Zipping",
    "Muffling",
    "Rolling",
    "Turning",
    "Composing",
    "Heating",
    "Cascading",
    "Linking",
    "Catching",
    "Waking",
    "Diving",
    "Rounding",
    "Tapping",
    "Browsing",
    "Brewing",
    "Drifting",
    "Hashing",
    "Solving",
    "Lifting",
    "Digesting",
    "Grooming",
    "Wrapping",
    "Curling",
    "Plumbing",
    "Firing",
    "Seeding",
    "Navigating",
    "Mapping",
    "Bending",
    "Gathering",
    "Churning",
    "Reeling",
    "Fusing",
    "Elevating",
    "Orbiting",
]


def random_verb() -> str:
    return random.choice(VERBS)


def random_verbs(n: int) -> list[str]:
    if n < 0:
        raise ValueError("n must be non-negative")
    if n > len(VERBS):
        raise ValueError(f"n ({n}) is larger than the available verbs ({len(VERBS)})")
    return random.sample(VERBS, n)
